name: CI/CD Pipeline
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build front-end artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checking out that code
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: cd frontend && npm i

      - name: Compile code
        run: cd frontend && npm run build
