name: CI/CD Pipeline
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build front-end artifact
    needs:
      - audit
    runs-on: ubuntu-latest
    steps:
      - name: Checking out that code
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: cd frontend && npm i

      - name: Compile code
        run: cd frontend && npm run build

  audit:
    name: Audit the frontend deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run an auidt
        run: cd frontend && npm audit --production

  lint:
      name: Ensure code style
      runs-on: ubuntu-latest
      needs: build 
      steps:
        - uses: actions/checkout@v3
        
        - uses: actions/setup-node@v3

        - name: Install deps
          run: cd frontend && npm i

        - name: Run the linter
          run: cd frontend && npm run lint
